version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    # Expose to host network for Windows WSL access
    network_mode: "host"

volumes:
  redis_data:
    driver: local