version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - linguify_network

networks:
  linguify_network:
    driver: bridge

volumes:
  redis_data:
    driver: local