name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db_linguify
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    defaults:
      run:
        working-directory: ./backend
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '1.7.1'

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          poetry install
          poetry add --group dev pytest-django pytest-mock flake8

      - name: Run linting
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      - name: Setup test environment
        run: |
          cp .env.example .env.test
          sed -i 's/DB_NAME=.*/DB_NAME=test_db_linguify/g' .env.test
          sed -i 's/DB_USER=.*/DB_USER=postgres/g' .env.test
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=postgres/g' .env.test
          sed -i 's/DB_HOST=.*/DB_HOST=localhost/g' .env.test
          sed -i 's/DB_PORT=.*/DB_PORT=5432/g' .env.test
          sed -i 's/DEBUG=.*/DEBUG=True/g' .env.test
          sed -i 's/DJANGO_ENV=.*/DJANGO_ENV=test/g' .env.test
          sed -i 's/AUTH0_DOMAIN=.*/AUTH0_DOMAIN=test.auth0.com/g' .env.test
          sed -i 's/AUTH0_CLIENT_ID=.*/AUTH0_CLIENT_ID=test_client_id/g' .env.test
          sed -i 's/AUTH0_CLIENT_SECRET=.*/AUTH0_CLIENT_SECRET=test_client_secret/g' .env.test
          sed -i 's/AUTH0_AUDIENCE=.*/AUTH0_AUDIENCE=https:\/\/test-api/g' .env.test
          sed -i 's/SECRET_KEY=.*/SECRET_KEY=test_secret_key_for_ci_environment/g' .env.test
          sed -i 's/AI_PROVIDER=.*/AI_PROVIDER=simulator/g' .env.test
          sed -i 's/REDIS_URL=.*/REDIS_URL=redis:\/\/localhost:6379\/1/g' .env.test
          sed -i 's/REDIS_PASSWORD=.*/REDIS_PASSWORD=/g' .env.test
          # Add testing-specific settings
          echo "TESTING=True" >> .env.test
          echo "ALLOWED_HOSTS=*" >> .env.test
          echo "CORS_ALLOWED_ORIGINS=http://localhost:3000" >> .env.test

      - name: Run migrations
        run: |
          set -a
          source .env.test
          set +a
          poetry run python manage.py migrate
        env:
          TEST_MODE: 'True'

      - name: Run tests
        run: |
          set -a
          source .env.test
          set +a
          poetry run python run_all_tests.py
        env:
          TEST_MODE: 'True'
          CI: 'True'
      
      # Génération de rapport supprimée car les fichiers ne sont pas générés correctement

      # Envoi des résultats de test simples
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/.pytest_cache
          retention-days: 3

  notify:
    name: Notify on failure
    needs: [test]
    if: failure()
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Create issue on test failure
        uses: actions/github-script@v7
        with:
          script: |
            const workflowName = "Backend CI";
            const runId = "${{ github.run_id }}";
            const branch = "${{ github.ref_name }}";
            const repo = context.repo;
            const issueTitle = `🚨 CI Failed: ${workflowName} on ${branch}`;
            const issueBody = `The CI workflow **${workflowName}** failed on the \`${branch}\` branch.

            **Run URL**: [View Failed Run](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId})

            **Time**: ${new Date().toISOString()}

            Please investigate the issue and fix the failing tests.`;

            await github.rest.issues.create({
              owner: repo.owner,
              repo: repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ["bug", "CI"]
            });