name: CI Failure Issue

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  report-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Create Issue on Failure
        uses: actions/github-script@v7
        with:
          script: |
            const workflowName = "${{ github.event.workflow_run.name }}";
            const runId = "${{ github.event.workflow_run.id }}";
            const repo = context.repo;
            const issueTitle = `🚨 Workflow Failed: ${workflowName}`;
            const issueBody = `The workflow **${workflowName}** failed on the \`main\` branch.

            **Run URL**: [View Failed Run](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${runId})

            **Time**: ${new Date().toISOString()}

            Please investigate the issue.`;

            await github.rest.issues.create({
              owner: repo.owner,
              repo: repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ["bug", "CI"]
            });
